version: '3.7'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8100:8100"
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
  database:
    image: postgres:12.2
    ports:
      - "5432:5432"
    volumes:
      - /Users/brandoncaton/projects/volumes/postgres:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: password
      
    
  
  